name: Build Docker images for AHK

on:
  push:
    paths:
      - "ahk/**"
      - "megoldas/**"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Login to GitHub Docker packages
        env:
          DOCKER_REG_USERNAME: ${{ secrets.DOCKER_REG_USERNAME }}
          DOCKER_REG_TOKEN: ${{ secrets.DOCKER_REG_TOKEN }}
        run: docker login docker.pkg.github.com -u $DOCKER_REG_USERNAME -p $DOCKER_REG_TOKEN
      - name: Build all images with compose
        run: |
          cd ahk/src
          docker-compose build
      - name: Test sample solution for TSQL
        run: docker run --rm -v $(pwd)/megoldas/Lab-MSSQL:/megoldas docker.pkg.github.com/bmeviauac01/laborok/lab-mssql:2020
      - name: Push Docker images
        run: |
          cd ahk/src
          docker-compose push
          docker logout docker.pkg.github.com
